server:
  port: 8082
spring:
  kafka:
    bootstrap-servers: localhost:9092
app:
  kafka:
    kafkaMessageProduceTopic: "order-status-topic"
    kafkaMessageConsumeTopic: "order-topic"
    kafkaMessageGroupId: "kafka-message-group-id"

